### ISSUE TITLE
Honor `$XDG_CONFIG_HOME` on MacOS

### ISSUE THREAD

**Issue by noahmayr** [MeirKriheli/rusmux#7]
Basically what the title says. The dirs and directories crates refuse to support users choosing their own config directory to be where most CLIs are storing their configs anyways: `~/.config/*` (see https://github.com/dirs-dev/directories-rs/issues/47 and https://github.com/dirs-dev/dirs-rs/issues/35)

If any other dirs (caches, data, state) are used, ideally support the other XDG env vars as well: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by MeirKriheli** [comment]
It's using the `directories` crate, which from what can see, rejected that request, so not sure what I've supposed to do, as I do not plan to maintain platform specific code for config directories.
